<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Sample.Interfaces\Sample.Interfaces.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <!-- IEntityTypeConfiguration only (solution-domain-configuration) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
