<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Modules\Sample\Sample.Application\Sample.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Sample\Sample.Interfaces\Sample.Interfaces.csproj" />
  </ItemGroup>
</Project>
