<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Sample.Domain.Rules\Sample.Domain.Rules.csproj" />
    <ProjectReference Include="..\Sample.Interfaces\Sample.Interfaces.csproj" />
  </ItemGroup>
</Project>
