<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="Ardalis.Specification" Version="10.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Sample.Domain\Sample.Domain.csproj" />
    <ProjectReference Include="..\Sample.Domain.Rules\Sample.Domain.Rules.csproj" />
    <ProjectReference Include="..\Sample.Interfaces\Sample.Interfaces.csproj" />
  </ItemGroup>
</Project>
